basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a project management system.
  termsOfService: http://swagger.io/terms/
  title: Project Management API
  version: "1.0"
paths: {}
swagger: "2.0"
